name: "parse and deploy"
on:
  schedule:
    - cron:  '05 4 * * *'
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: parse options and create search
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          ruby scripts/parse_appendix.rb
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
