name: "parse and deploy"
on:
  schedule:
    - cron:  '05 4 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: parse options and create search
    steps:

      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: master-options
        run: ./scripts/build_hm_options.sh

      - name: update gitignore
        run: echo result > .gitignore

      - name: release-options
        env:
          HM_RELEASE: release-23.11
        run: ./scripts/build_hm_options.sh

      - name: release-options
        env:
          HM_RELEASE: release-23.05
        run: ./scripts/build_hm_options.sh
      #
      #      - name: master-options
      #        env:
      #          RELEASE: release-22.11
      #        run: ./scripts/build_hm_options.sh
      #
      #      - name: master-options
      #        env:
      #          RELEASE: release-22.05
      #        run: ./scripts/build_hm_options.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages-${{ github.ref_name }}
          publish_dir: .
