name: "parse and deploy"
on:
  schedule:
    - cron:  '05 4 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: parse options and create search
    steps:

      - uses: actions/checkout@v4

      #      - uses: cachix/install-nix-action@v25
        #        with:
#          nix_path: nixpkgs=channel:nixos-unstable
#     - uses: cachix/cachix-action@v13
#       with:
#         name: nix-community
#         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        #
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: master-options
        run: ./scripts/build_hm_options.sh

      - name: remove gitignore
        run: rm .gitignore

      #      - name: master-options
      #        env:
      #          RELEASE: release-23.11
      #        run: ./scripts/build_hm_options.sh
      #
      #      - name: master-options
      #        env:
      #          RELEASE: release-22.11
      #        run: ./scripts/build_hm_options.sh
      #
      #      - name: master-options
      #        env:
      #          RELEASE: release-22.05
      #        run: ./scripts/build_hm_options.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages-${{ github.ref_name }}
          publish_dir: .
