name: "parse and deploy"
on:
  schedule:
    - cron:  '05 4 * * *'
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: parse options and create search
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: ruby scripts/parse_appendix.rb && bash scripts/commitpush.sh
